name: Generate Snake

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Generate snake
              uses: Platane/snk@v3
              with:
                  github_user_name: ${{ github.repository_owner }}
                  outputs: dist/snake.svg

            - name: Push to dist branch
              uses: crazy-max/ghaction-github-pages@v4
              with:
                  target_branch: dist
                  build_dir: dist
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
